In [4]:
import numpy as np
import pandas as pd

## Task 1: Pandas → NumPy (Bridge Task)

In [77]:
df = pd.read_csv('car-sales-missing-data.csv')
df

Make Colour  Odometer  Doors    Price
0  Toyota  White  150043.0    4.0   $4,000
1   Honda    Red   87899.0    4.0   $5,000
2  Toyota   Blue       NaN    3.0   $7,000
3     BMW  Black   11179.0    5.0  $22,000
4  Nissan  White  213095.0    4.0   $3,500
5  Toyota  Green       NaN    4.0   $4,500
6   Honda    NaN       NaN    4.0   $7,500
7   Honda   Blue       NaN    4.0      NaN
8  Toyota  White   60000.0    NaN      NaN
9     NaN  White   31600.0    4.0   $9,700

In [78]:
df['Price']=df['Price'].str.replace('$', '', regex = False)
df['Price']=df['Price'].str.replace(",", "", regex = False) 
df['Price']= df['Price'].astype(float)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Make      9 non-null      object 
 1   Colour    9 non-null      object 
 2   Odometer  6 non-null      float64
 3   Doors     9 non-null      float64
 4   Price     8 non-null      float64
dtypes: float64(3), object(2)
memory usage: 528.0+ bytes


In [79]:
df['Odometer'].fillna(df['Odometer'].median(), inplace = True)
df['Doors'].fillna(df['Doors'].mode()[0], inplace = True)
df['Price'].fillna(df['Price'].median(), inplace = True)


In [80]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Make      9 non-null      object 
 1   Colour    9 non-null      object 
 2   Odometer  10 non-null     float64
 3   Doors     10 non-null     float64
 4   Price     10 non-null     float64
dtypes: float64(3), object(2)
memory usage: 528.0+ bytes


In [103]:
np_arr = df.select_dtypes(include = ['float', 'int']).to_numpy(dtype='int')
np_arr

array([[150043,      4,   4000],
       [ 87899,      4,   5000],
       [ 73949,      3,   7000],
       [ 11179,      5,  22000],
       [213095,      4,   3500],
       [ 73949,      4,   4500],
       [ 73949,      4,   7500],
       [ 73949,      4,   6000],
       [ 60000,      4,   6000],
       [ 31600,      4,   9700]])

## Task 2: NumPy Statistics

Compute mean
Compute median
Compute standard deviation

In [104]:
np.mean(np_arr)

30828.4

In [105]:
np.median(np_arr)

6000.0

In [106]:
np_arr.std()

49854.15271409193

## Task 3: Boolean Masking (NumPy style)

In [107]:
np_arr.shape

(10, 3)

In [108]:
price_col = np_arr[:,2]
mean_price = np.mean(price_col)
filtered_price = np_arr[price_col>mean_price]
filtered_price

array([[11179,     5, 22000],
       [31600,     4,  9700]])

In [109]:
price_col

array([ 4000,  5000,  7000, 22000,  3500,  4500,  7500,  6000,  6000,
        9700])

## Task 4: Column-wise Scaling (Manual)

In [120]:
# Scale the Odometer column using this formula:
scaled_odo= (np_arr[:,0] - np.mean(np_arr[:,0]))/np.std(np_arr[:,0]) 
scaled_odo

array([ 1.18700154,  0.05358139, -0.20084722, -1.34568474,  2.33698235,
       -0.20084722, -0.20084722, -0.20084722, -0.45525758, -0.97323409])

## Task 5: Back to Pandas (ML Thinking)

In [121]:
# Take the scaled Odometer values and: Replace the original Odometer column in df
df["Odometer"] = scaled_odo
df.head()


Make Colour  Odometer  Doors    Price
0  Toyota  White  1.187002    4.0   4000.0
1   Honda    Red  0.053581    4.0   5000.0
2  Toyota   Blue -0.200847    3.0   7000.0
3     BMW  Black -1.345685    5.0  22000.0
4  Nissan  White  2.336982    4.0   3500.0