## Import the libraries

In [1]:
import numpy as np

## Task 1: Creating Arrays

In [8]:
# Create arrays
a = np.array([1, 2, 3])
b = np.array([[1, 2], [3, 4]])

zeros = np.zeros((3, 4))
ones = np.ones((2, 3))
rand = np.random.rand(2, 2)

In [9]:
# Print the arrays
a, b, zeros, ones, rand

(array([1, 2, 3]),
 array([[1, 2],
        [3, 4]]),
 array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([[0.50705475, 0.44926967],
        [0.04581563, 0.44935966]]))

In [10]:
# Check shape with .shape
a.shape, b.shape

((3,), (2, 2))

## Task 2: Array Properties

In [12]:
# Check the dimensions with .ndim
a.ndim, b.ndim, zeros.ndim, ones.ndim, rand.ndim

(1, 2, 2, 2, 2)

In [14]:
# Check the array properties
a.shape, a.ndim, a.size, a.dtype

((3,), 1, 3, dtype('int32'))

## Task 3: Indexing & Slicing

In [15]:
arr = np.array([10, 20, 30, 40, 50])
arr[1]

20

In [16]:
arr[1:4]

array([20, 30, 40])

In [17]:
arr[-1]

50

In [23]:
arr[-1],arr[-3]

(50, 30)

In [116]:
matt = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

In [117]:
matt[0,1], matt[1,1], matt[2,1]

(2, 5, 8)

`: → all rows`

`1 → column index`

In [118]:
matt[:1], matt[1:], matt[:-1], matt[-1:], matt[:, 1]

(array([[1, 2, 3]]),
 array([[4, 5, 6],
        [7, 8, 9]]),
 array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9]]),
 array([2, 5, 8]))

## Task 4: Boolean Masking

In [43]:
arr = np.array([5, 10, 15, 20, 25])

arr[arr>15]

array([20, 25])

## Task 5: Vectorized Operations

In [45]:
result = []
for x in arr:
    result.append(x*2)
result

[10, 20, 30, 40, 50]

In [48]:
arr*2
result = arr*2
result

array([10, 20, 30, 40, 50])

In [49]:
result = arr+2
result

array([ 7, 12, 17, 22, 27])

In [50]:
result = arr**2
result

array([ 25, 100, 225, 400, 625])

In [51]:
result = arr//2
result

array([ 2,  5,  7, 10, 12], dtype=int32)

## Task 6: Aggregations & Axis

In [52]:
matt = np.array([[1,2,3],
                 [4, 5, 6]])

In [54]:
np.sum(matt)

21

In [59]:
np.sum(matt, axis=0), np.sum(matt, axis = 1)

(array([5, 7, 9]), array([ 6, 15]))

axis=0 → column-wise

axis=1 → row-wise

In [57]:
np.mean(matt)

3.5

In [58]:
np.max(matt)

6

## Task 7: Reshaping & Broadcasting

In [60]:
arr = np.array([1, 2, 3, 4, 5, 6])

arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
arr.reshape(-1, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [66]:
matt = np.array([[1, 2, 3],
               [4, 5, 6]])
matt+10

array([[11, 12, 13],
       [14, 15, 16]])

## Task 8: Basic Linear Algebra

In [67]:
A = np.array([[1,2],
             [3,4]])

B = np.array([[5, 6],
             [7, 8]])

In [68]:
A@B

array([[19, 22],
       [43, 50]])

@ == Dot product 

In [69]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [74]:
np.linalg.inv(A), 

(array([[-2. ,  1. ],
        [ 1.5, -0.5]]),)

In [71]:
np.invert(B)

array([[-6, -7],
       [-8, -9]])

In [ ]:
np.linalg

## Mini Practice

In [96]:
# Create a (3,3) random matrix

mat = np.array([[1, 2, 3],
               [4,5,6],
               [7, 8, 9]])

In [114]:
# Extract the second column
mat[:,1]

array([2, 5, 8])

In [101]:
# Multiply entire matrix by 0.1
print(mat*0.1)


[[0.1 0.2 0.3]
 [0.4 0.5 0.6]
 [0.7 0.8 0.9]]


In [119]:
# Compute row-wise mean
np.mean(mat[0]), np.mean(mat[1]), np.mean(mat[2])

(2.0, 5.0, 8.0)

In [111]:
mean_result = [np.mean(mat[i]) for i in range (mat.ndim+1)]
mean_result

[2.0, 5.0, 8.0]

## Corrections

In [122]:
np.mean(mat, axis =1)

array([2., 5., 8.])

In [124]:
mean_result = [np.mean(mat[i]) for i in range(mat.shape[0])]
mean_result

[2.0, 5.0, 8.0]

###  Always think in (rows, columns)
### Prefer:
`np.mean(mat, axis=1)`

over loops

## Extra Practice Questions

### Q1. Axis intuition

In [127]:
X = np.random.randint(1, 10, size=(4,3))
X

array([[9, 5, 4],
       [9, 5, 9],
       [6, 3, 2],
       [7, 5, 2]])

In [131]:
# Compute row wise mean
rwm = np.mean(X, axis =1)


In [132]:
# Compute column wise mean
cwm = np.mean(X, axis = 0)

In [133]:
rwm, cwm, rwm.shape, cwm.shape

(array([6.        , 7.66666667, 3.66666667, 4.66666667]),
 array([7.75, 4.5 , 4.25]),
 (4,),
 (3,))

### Q2. Shape awareness

In [136]:
arr = np.random.randint(1, 10, size = (6,))
arr

array([4, 8, 4, 7, 8, 5])

In [137]:
# Convert it to (6,1)
arr.reshape(6,1)

array([[4],
       [8],
       [4],
       [7],
       [8],
       [5]])

In [138]:
# Convert it to (1,6)
arr.reshape(1,6)

array([[4, 8, 4, 7, 8, 5]])

#### Explain where each is used in ML
-> Can be used to transform the shape of the images, input matrix. While computation of 2 matrices if the shape is mismatched then reshape can be used to make it ready for computation.

### Q3. Feature normalization

In [141]:
# Normalize this matrix to range [0,1]:
X = np.array([[1, 2, 3],
             [4, 5, 6],
            [7, 8, 9]])
X

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

`Xnorm=Xmax−Xmin/X−Xmin`

In [145]:
# Step 1: Find min and max
x_min = X.min()
x_max = X.max()
x_min , x_max

(1, 9)

In [150]:
#Step 2: Apply vectorized formula
X_norm = (X-x_min)/(x_max - x_min)
X_norm, X_norm.min(), X_norm.max()

(array([[0.   , 0.125, 0.25 ],
        [0.375, 0.5  , 0.625],
        [0.75 , 0.875, 1.   ]]),
 0.0,
 1.0)

## This is exactly what:

    MinMaxScaler does
    
    Feature scaling before:
    
    Gradient Descent
    
    Neural Networks
    
    Distance-based models

## Q4. Outlier removal

In [152]:
data = np.array([12, 15, 18, 120, 17, 16, 130])
data[data>30 # Greater than 30

array([120, 130])

In [154]:
data[data<=30] # less that equal to 30

array([12, 15, 18, 17, 16])

In [156]:
#Explicit mask
mask = data <=30 
otl = data[mask]
otl

array([12, 15, 18, 17, 16])

###  Why This Works 
        
        data > 30 creates a boolean array
        
        NumPy uses this boolean array to select elements
        
        This is called boolean indexing
### This is used in:
        
        Outlier removal
        
        Missing value handling
        
        Dataset cleaning
        
        Feature selection

## Q5. Linear regression prediction

In [161]:
X = np.array([[1, 2],
             [2, 3],
             [3, 4]])

In [162]:
w = np.array([0.5, 1.0])
b=2

In [166]:
pred  = b +(np.dot(X,w)) 
pred

array([4.5, 6. , 7.5])

In [168]:
pred = X@w + b
pred

array([4.5, 6. , 7.5])

###  X@w + b is the core of:

    Linear Regression
    
    Logistic Regression
    
    Neural network forward pass
    
    Everything later is just:
    
    Loss functions
    
    Gradients
    
    Optimization

In [170]:
w = w.reshape(-1,1)
pred =  X@w + b
pred

array([[4.5],
       [6. ],
       [7.5]])

In [174]:
pred.shape

(3, 1)

## Q6. Mean Squared Error (MSE)

In [177]:
y_true = np.array([3, 5, 7])
y_pred = np.array([2.5, 5.5, 6])

mse = np.mean((y_true-y_pred)**2)
mse

0.5

## `mse = np.mean((y_true-y_pred)**2)` is what:

    Linear Regression minimizes
    
    Neural networks optimize (via gradients)
    
    Frameworks like TensorFlow compute internally
    
    If this logic is wrong → entire model training collapses.

## Q7. Debug this

In [209]:
X = np.random.rand(5,3)
w = np.random.rand(5)

In [210]:
X@w

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 5 is different from 3)

In [202]:
X.reshape(3,5)

array([[0.13278472, 0.93687437, 0.14102237, 0.96769586, 0.17182343],
       [0.55617407, 0.11791738, 0.50758618, 0.89701264, 0.11744928],
       [0.29833924, 0.8106522 , 0.83177516, 0.54004962, 0.04358858]])

#### X = np.random.rand(5, 3)   # (samples=5, features=3)
#### w = np.random.rand(5)      # ❌ wrong
   
    The operation fails due to a dimensionality mismatch.
    For matrix multiplication, the number of columns in the first matrix must equal the number of elements (or rows) in the second.
    Here, X has shape (5, 3), meaning 3 features, but w incorrectly has 5 elements.
    To fix this, w must have 3 elements (one per feature), so its shape should be (3,) or (3,1).**

In [211]:
# Option 1: 1D weight vector (most common)
w = np.random.rand(3)
X@w

array([0.61154421, 0.52375343, 0.46218591, 0.95191177, 0.60517109])

In [213]:
## Option 2: Column vector (deep learning style)
w = np.random.rand(3,1)
X@w

array([[0.80196185],
       [0.61624713],
       [0.54118689],
       [0.99147037],
       [0.91276109]])

#### Why option 2 is called Deep learning style ?
    Reason 👇
         Deep learning frameworks (TensorFlow, PyTorch) always treat:
            1. inputs
            2. weights
            3. activations
            4. gradients
                as 2D tensors (or higher) — never ambiguous 1D vectors.
            
         In deep learning:
            1. Shapes must be explicit   
            2. Broadcasting ambiguity is avoided
            3. Backpropagation relies on strict tensor algebra
                    So weights are represented as column vectors or matrices, not 1D arrays.
                    
#### What is option 1 called ?
    This is classical ML / NumPy convenience style
        Why it exists:
            1.NumPy allows 1D vectors
            2. Cleaner syntax
            3. Less typing
       
        Perfect for:
            1.Linear Regression
            2. Logistic Regression
            3. Quick experiments
            4. Math derivations

#### Why Deep Learning Avoids 1D Vectors ?
`w.T == w    # for 1D arrays`
❌ Transpose does nothing — dangerous for gradients.

`w = np.random.rand(3,1)`
`W.T` #->(1,3)
✅ Transpose is meaningful.

Gradients require this distinction.

`Deep learning frameworks use column vectors and matrices because they enforce explicit tensor dimensions, which are essential for stable matrix multiplications and backpropagation, whereas 1D vectors are a NumPy convenience often used in classical machine learning.`